# -*- coding: utf-8 -*-
"""customer_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5Wyb7atmdbnCh13f3zZuSz64Q9NYQrh

# Customer Churn Prediction using Random Forest

## 1. Introduction
**Concept of Customer Churn:** Customer churn refers to the percentage of customers who stop using a company's product or service during a certain timeframe.

**Relevance for Businesses:** Predicting churn is critical because acquiring new customers is significantly more expensive than retaining existing ones. By identifying at-risk customers, businesses can implement targeted retention strategies.

**Why Random Forest:** Random Forest is an ensemble learning method that builds multiple decision trees and merges them together to get a more accurate and stable prediction. It handles both categorical and numerical data well, is robust to outliers, and automatically provides a feature importance ranking, making it ideal for understanding the key drivers of churn.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc

df = pd.read_csv('Customertravel.csv')
print(df.head())
print(df.describe())
print(df.info())
print(df.isnull().sum())

df = df.dropna()
X = df.drop('Target', axis=1)
y = df['Target']
X = pd.get_dummies(X, drop_first=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

plt.figure(figsize=(6, 4))
sns.countplot(x='Target', data=df)
plt.title('Target Distribution')
plt.show()

plt.figure(figsize=(6, 4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.show()

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)
plt.figure(figsize=(6, 4))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

feature_importances = pd.Series(rf_model.feature_importances_, index=X.columns).sort_values(ascending=False).head(10)
plt.figure(figsize=(8, 6))
sns.barplot(x=feature_importances, y=feature_importances.index)
plt.title('Top 10 Feature Importances')
plt.show()

import pickle

with open('model.pkl', 'wb') as file:
    pickle.dump(rf_model, file)